#ifndef BUILDCONFIG_SOURCE_H
#define BUILDCONFIG_SOURCE_H


#define APP_VERSION  "@EDITOR_VERSION@"
#define BUILD_NUM  @BUILD_NUM@
#define REMOTE_BUILD  @RemoteBuild@
#define IS_RELEASE  @IS_RELEASE@

#endif // BUILDCONFIG_SOURCE_H
